name = "lisas-recipe-book"
compatibility_date = "2026-09-27"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "lisas-recipe-book"
database_id = "c4db9d95-dcdd-4ea8-b30a-02e61c2f76be"
