const gymNote = "A plate of meat, fish, eggs, or beans for a training day. This is food from the kitchen, not a vitamin plan.";

export const GYM = [
  {
    id: "grilled-chicken-rice",
    title: "Grilled Chicken and Rice",
    cuisine: "gym",
    category: "Mains",
    summary: "Chicken breast seared hard, sliced over rice with peppers. A plain protein plate Benito can eat after the gym.",
    yieldText: "4 servings",
    prepMinutes: 15,
    cookMinutes: 25,
    ingredients: [
      "1 1/2 lb boneless chicken breast",
      "1 teaspoon kosher salt",
      "1 teaspoon black pepper",
      "1 teaspoon paprika",
      "1 tablespoon oil",
      "2 cups cooked rice",
      "1 red bell pepper, sliced",
      "1 green bell pepper, sliced",
      "1 lime"
    ],
    steps: [
      "Salt and pepper the chicken and dust it with paprika.",
      "Heat the oil in a skillet over medium-high. Cook the chicken 6 to 7 minutes a side, until the center is 165°F. Rest 5 minutes, then slice.",
      "In the same skillet, cook the peppers 4 minutes, until they soften.",
      "Spoon rice into bowls. Lay the chicken and peppers on top. Squeeze the lime over the plate."
    ],
    notes: gymNote,
    image: "/images/grilled-chicken-rice.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "egg-white-skillet",
    title: "Egg White Vegetable Skillet",
    cuisine: "gym",
    category: "Breakfast",
    summary: "A heap of egg whites with spinach, tomato, and a little cheese. High protein, and ready before a morning workout.",
    yieldText: "2 servings",
    prepMinutes: 10,
    cookMinutes: 10,
    ingredients: [
      "8 egg whites, or 1 cup liquid egg whites",
      "2 whole eggs",
      "1 teaspoon oil",
      "2 cups baby spinach",
      "1 cup chopped tomato",
      "1/4 cup shredded cheddar",
      "1/4 teaspoon kosher salt",
      "Black pepper"
    ],
    steps: [
      "Warm the oil in a nonstick skillet. Wilt the spinach and cook the tomato 2 minutes.",
      "Beat the egg whites with the whole eggs, salt, and pepper. Pour them over the vegetables.",
      "Cook on medium, lifting the edges, until just set. Scatter the cheese and cover 1 minute.",
      "Slide onto plates. Pepper the top."
    ],
    notes: gymNote,
    image: "/images/egg-white-skillet.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "salmon-sweet-potato",
    title: "Salmon and Sweet Potato",
    cuisine: "gym",
    category: "Mains",
    summary: "Roasted salmon beside a baked sweet potato and a pile of broccoli. Simple food that fills you up after lifting.",
    yieldText: "2 servings",
    prepMinutes: 10,
    cookMinutes: 25,
    ingredients: [
      "2 salmon fillets, about 6 oz each",
      "2 medium sweet potatoes",
      "3 cups broccoli florets",
      "1 tablespoon oil",
      "1/2 teaspoon kosher salt",
      "1/2 teaspoon black pepper",
      "1 lemon"
    ],
    steps: [
      "Heat the oven to 425°F. Prick the sweet potatoes and bake them 25 minutes, until soft.",
      "Toss the broccoli with half the oil. Spread it on a sheet pan for the last 12 minutes.",
      "Rub the salmon with the rest of the oil, salt, and pepper. Bake it 10 to 12 minutes, until it flakes.",
      "Plate the potato, broccoli, and salmon. Squeeze lemon over the fish."
    ],
    notes: gymNote,
    image: "/images/salmon-sweet-potato.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "turkey-bean-bowl",
    title: "Turkey and Black Bean Bowl",
    cuisine: "gym",
    category: "Mains",
    summary: "Lean ground turkey, black beans, rice, and salsa in one bowl. A fast plate after work.",
    yieldText: "4 servings",
    prepMinutes: 10,
    cookMinutes: 20,
    ingredients: [
      "1 lb lean ground turkey",
      "1 teaspoon chili powder",
      "1/2 teaspoon cumin",
      "1/2 teaspoon kosher salt",
      "1 can (15 oz) black beans, rinsed",
      "2 cups cooked rice",
      "1 cup corn",
      "1 cup table salsa",
      "1/4 cup chopped cilantro",
      "1 lime"
    ],
    steps: [
      "Brown the turkey in a skillet, breaking it up, until no pink remains. Stir in the chili powder, cumin, and salt.",
      "Add the beans and corn. Warm them through, about 3 minutes.",
      "Build bowls with rice, the turkey mixture, and salsa.",
      "Top with cilantro and a squeeze of lime."
    ],
    notes: gymNote,
    image: "/images/turkey-bean-bowl.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "yogurt-berry-bowl",
    title: "Greek Yogurt Berry Bowl",
    cuisine: "gym",
    category: "Breakfast",
    summary: "Plain Greek yogurt with berries, oats, and a spoon of peanut butter. A cold breakfast with real protein.",
    yieldText: "1 serving",
    prepMinutes: 5,
    cookMinutes: 0,
    ingredients: [
      "1 cup plain Greek yogurt",
      "1/2 cup mixed berries",
      "2 tablespoons rolled oats",
      "1 tablespoon peanut butter",
      "1 teaspoon honey, optional"
    ],
    steps: [
      "Spoon the yogurt into a bowl.",
      "Scatter the berries and oats over the top.",
      "Add the peanut butter. Drizzle honey if you want it sweeter."
    ],
    notes: `${gymNote} Skip the honey if you want it less sweet.`,
    image: "/images/yogurt-berry-bowl.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "shrimp-vegetable-skillet",
    title: "Shrimp and Vegetable Skillet",
    cuisine: "gym",
    category: "Mains",
    summary: "Shrimp cooked fast with zucchini, peppers, and garlic. Light, and high in protein.",
    yieldText: "3 servings",
    prepMinutes: 15,
    cookMinutes: 12,
    ingredients: [
      "1 lb large shrimp, peeled",
      "1 tablespoon oil",
      "2 zucchini, sliced",
      "1 red bell pepper, sliced",
      "3 garlic cloves, sliced",
      "1/2 teaspoon kosher salt",
      "1/4 teaspoon black pepper",
      "1 lemon",
      "2 cups cooked rice, optional"
    ],
    steps: [
      "Pat the shrimp dry. Heat the oil in a large skillet over medium-high.",
      "Cook the zucchini and pepper 4 minutes. Add the garlic for 30 seconds.",
      "Add the shrimp, salt, and pepper. Cook 2 to 3 minutes a side, until the shrimp are pink and firm.",
      "Squeeze the lemon over the skillet. Serve as it is, or over rice."
    ],
    notes: gymNote,
    image: "/images/shrimp-vegetable-skillet.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "chicken-quinoa",
    title: "Chicken and Quinoa",
    cuisine: "gym",
    category: "Mains",
    summary: "Sliced chicken over quinoa with cucumber and herbs. A clean plate you can pack for the next day.",
    yieldText: "4 servings",
    prepMinutes: 15,
    cookMinutes: 25,
    ingredients: [
      "1 cup quinoa, rinsed",
      "2 cups water",
      "1/2 teaspoon kosher salt",
      "1 lb boneless chicken breast",
      "1 tablespoon oil",
      "1 teaspoon black pepper",
      "1 cucumber, diced",
      "1/4 cup chopped parsley",
      "2 tablespoons lemon juice"
    ],
    steps: [
      "Simmer the quinoa, water, and a pinch of the salt, covered, 15 minutes. Rest off the heat 5 minutes and fluff.",
      "Salt and pepper the chicken. Sear it in the oil 6 to 7 minutes a side, to 165°F. Rest, then slice.",
      "Toss the quinoa with cucumber, parsley, lemon juice, and the rest of the salt.",
      "Top with the chicken."
    ],
    notes: gymNote,
    image: "/images/chicken-quinoa.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "tuna-white-bean",
    title: "Tuna and White Bean Salad",
    cuisine: "gym",
    category: "Mains",
    summary: "Canned tuna, white beans, olive oil, and lemon. No cooking, and it packs a lot of protein.",
    yieldText: "2 servings",
    prepMinutes: 10,
    cookMinutes: 0,
    ingredients: [
      "2 cans (5 oz) tuna in water, drained",
      "1 can (15 oz) white beans, rinsed",
      "2 tablespoons olive oil",
      "1 tablespoon lemon juice",
      "1/4 red onion, minced",
      "2 tablespoons chopped parsley",
      "1/4 teaspoon kosher salt",
      "Black pepper"
    ],
    steps: [
      "Break the tuna into a bowl with the beans.",
      "Stir in the oil, lemon, onion, parsley, salt, and pepper.",
      "Taste and add more lemon if you want it brighter.",
      "Serve cold, with toast or over greens."
    ],
    notes: gymNote,
    image: "/images/tuna-white-bean.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "turkey-meatballs-greens",
    title: "Turkey Meatballs and Greens",
    cuisine: "gym",
    category: "Mains",
    summary: "Baked turkey meatballs with garlic greens. A hot supper that is still a training plate.",
    yieldText: "4 servings",
    prepMinutes: 20,
    cookMinutes: 22,
    ingredients: [
      "1 lb lean ground turkey",
      "1/2 cup rolled oats",
      "1 egg",
      "1 teaspoon kosher salt",
      "1 teaspoon black pepper",
      "1 teaspoon Italian seasoning",
      "1 tablespoon oil",
      "8 cups chopped greens, such as kale or chard",
      "2 garlic cloves, sliced",
      "1/4 cup water"
    ],
    steps: [
      "Heat the oven to 400°F. Mix the turkey, oats, egg, salt, pepper, and seasoning. Roll 16 meatballs.",
      "Set them on a lined sheet pan and bake 18 to 22 minutes, until the center is 165°F.",
      "While they bake, warm the oil and garlic. Add the greens and water. Cover and cook 5 minutes, until tender.",
      "Salt the greens lightly. Serve the meatballs on the greens."
    ],
    notes: gymNote,
    image: "/images/turkey-meatballs-greens.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "cottage-cheese-plate",
    title: "Cottage Cheese Protein Plate",
    cuisine: "gym",
    category: "Breakfast",
    summary: "Cottage cheese with tomato, cucumber, and a boiled egg. A cold plate you can eat standing up.",
    yieldText: "1 serving",
    prepMinutes: 10,
    cookMinutes: 10,
    ingredients: [
      "1 cup low-fat cottage cheese",
      "1 hard-boiled egg, halved",
      "1/2 cup cherry tomatoes, halved",
      "1/2 cucumber, sliced",
      "Black pepper",
      "A pinch of kosher salt"
    ],
    steps: [
      "Boil the egg 10 minutes if it is not already cooked. Cool it and halve it.",
      "Spoon the cottage cheese onto a plate.",
      "Add the egg, tomatoes, and cucumber.",
      "Pepper the cheese. Salt the vegetables, not the cheese."
    ],
    notes: gymNote,
    image: "/images/cottage-cheese-plate.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  }
];
