import { STAPLES } from "./staples.js";
import { MORE } from "./more-plates.js";

const commons = "Wikimedia Commons";
const book = "Photograph for Lisa's Recipe Book";

const BOOK = [
  {
    id: "oak-smoked-brisket",
    title: "Oak-Smoked Beef Brisket",
    cuisine: "texas",
    category: "Mains",
    summary: "A whole packer brisket seasoned with salt and coarse pepper, smoked low over oak until the bark is set and the flat slices with a juicy smoke ring.",
    yieldText: "12–16 servings",
    prepMinutes: 30,
    cookMinutes: 720,
    ingredients: [
      "1 whole packer brisket, 12–14 lb",
      "1/4 cup coarse kosher salt",
      "1/4 cup coarse black pepper",
      "2 tablespoons granulated garlic (optional)",
      "Oak or post oak wood chunks",
      "Butcher paper for the wrap"
    ],
    steps: [
      "Trim the brisket, leaving about 1/4 inch of fat on the fat cap. Mix the salt and pepper and coat every surface.",
      "Set the smoker at 250°F with a clean oak fire. Place the brisket fat-cap up and smoke until the bark is dark and the thickest part reads about 165–175°F.",
      "Wrap tightly in butcher paper and return it to the pit until a probe slides into the flat like soft butter, usually 200–205°F.",
      "Rest, still wrapped, in a dry cooler for at least 1 hour and up to 3 hours.",
      "Slice the flat against the grain and the point a little thicker. Serve the burnt ends to the person who tended the fire."
    ],
    notes: "Texas barbecue does not need sauce on the board. A vinegar hot sauce belongs on the side.",
    image: "/images/brisket.jpg",
    imageCredit: book,
    sourceUrl: "https://en.wikipedia.org/wiki/Brisket",
    sourceTitle: "Brisket"
  },
  {
    id: "chicken-fried-steak",
    title: "Chicken Fried Steak and Cream Gravy",
    cuisine: "texas",
    category: "Mains",
    summary: "Tenderized cube steak in a peppery crust, fried hard, then covered with the cream gravy made from the same pan.",
    yieldText: "4 servings",
    prepMinutes: 25,
    cookMinutes: 25,
    ingredients: [
      "4 cube steaks, about 5 oz each",
      "1 1/2 cups all-purpose flour, divided",
      "1 1/2 teaspoons kosher salt",
      "2 teaspoons coarse black pepper",
      "1 teaspoon garlic powder",
      "1 teaspoon paprika",
      "2 large eggs",
      "3/4 cup buttermilk",
      "Neutral oil for frying",
      "2 1/2 cups whole milk",
      "Mashed potatoes, for serving"
    ],
    steps: [
      "Season the steaks with salt. Mix 1 cup flour with the pepper, garlic powder, paprika, and a pinch of salt.",
      "Beat the eggs with the buttermilk. Dredge each steak in flour, then egg, then flour again.",
      "Fry in 1/2 inch of oil at 350°F until deep golden, about 3–4 minutes a side. Drain on a rack.",
      "Pour off all but 3 tablespoons of drippings. Whisk in 1/3 cup flour and cook 1 minute. Whisk in the milk and simmer until the gravy coats a spoon. Season boldly with pepper.",
      "Return the steaks to the gravy just long enough to warm them, and serve over mashed potatoes."
    ],
    notes: "The gravy should taste like pepper, not like plain milk.",
    image: "/images/chicken-fried-steak.jpg",
    imageCredit: commons,
    sourceUrl: "https://en.wikipedia.org/wiki/Chicken-fried_steak",
    sourceTitle: "Chicken-fried steak"
  },
  {
    id: "texas-chili",
    title: "Texas Chili, No Beans",
    cuisine: "texas",
    category: "Mains",
    summary: "A thick chili gravy of beef, dried chiles, and cumin. Beans, if anyone insists, are served on the side.",
    yieldText: "8 servings",
    prepMinutes: 30,
    cookMinutes: 180,
    ingredients: [
      "3 lb beef chuck, cut in 1/2-inch pieces",
      "2 tablespoons bacon drippings or oil",
      "1 large onion, chopped",
      "6 garlic cloves, minced",
      "3 dried ancho chiles",
      "2 dried guajillo chiles",
      "2 tablespoons chili powder",
      "1 tablespoon ground cumin",
      "1 teaspoon Mexican oregano",
      "2 cups beef broth",
      "1 tablespoon masa harina",
      "Salt, saltines, and chopped onion for the table"
    ],
    steps: [
      "Toast the dried chiles in a dry skillet, stem and seed them, then soak in hot water 20 minutes. Blend with a little soaking water into a smooth paste.",
      "Brown the beef in batches in the drippings. Soften the onion in the same pot, then add the garlic, chili powder, and cumin.",
      "Return the beef, add the chile paste, oregano, and broth. Simmer gently, partly covered, for 2 1/2 to 3 hours until the beef is tender and the gravy is thick.",
      "Stir the masa with a splash of water and whisk it in. Simmer 10 minutes more. Salt to taste.",
      "Serve in bowls with saltines and raw onion. Keep the beans in another pot."
    ],
    notes: "A true Texas bowl is a chili gravy, not a soup.",
    image: "/images/chili.jpg",
    imageCredit: book,
    sourceUrl: "https://en.wikipedia.org/wiki/Chili_con_carne",
    sourceTitle: "Chili con carne"
  },
  {
    id: "chicken-fajitas",
    title: "Sizzling Chicken Fajitas",
    cuisine: "texas",
    category: "Mains",
    summary: "Skirt-style strips of chicken with charred onion and bell pepper, piled onto warm flour tortillas. This is the South Texas skillet.",
    yieldText: "6 servings",
    prepMinutes: 20,
    cookMinutes: 20,
    ingredients: [
      "2 lb boneless chicken thighs",
      "3 tablespoons oil",
      "3 tablespoons lime juice",
      "2 teaspoons chili powder",
      "1 teaspoon ground cumin",
      "1 teaspoon kosher salt",
      "2 bell peppers, sliced",
      "1 large onion, sliced",
      "Warm flour tortillas",
      "Salsa, cilantro, and lime wedges"
    ],
    steps: [
      "Toss the chicken with 2 tablespoons oil, the lime juice, chili powder, cumin, and salt. Rest 20 minutes, or overnight.",
      "Sear the chicken in a very hot cast-iron skillet until browned and just cooked through. Rest and slice.",
      "In the same skillet, char the peppers and onion in the remaining oil until sweet and blackened at the edges.",
      "Return the chicken to the pan so it sizzles.",
      "Serve straight from the skillet with warm tortillas."
    ],
    notes: "The photograph is chicken, so this plate stays chicken. Beef skirt steak uses the same peppers and the same heat.",
    image: "/images/fajitas.jpg",
    imageCredit: commons,
    sourceUrl: "https://en.wikipedia.org/wiki/Fajita",
    sourceTitle: "Fajita"
  },
  {
    id: "king-ranch-chicken",
    title: "King Ranch Chicken",
    cuisine: "texas",
    category: "Mains",
    summary: "The church-supper casserole: tortillas, chicken, a creamy tomato-chile sauce, and a thick cap of cheese.",
    yieldText: "8 servings",
    prepMinutes: 30,
    cookMinutes: 40,
    ingredients: [
      "1 rotisserie chicken, meat shredded",
      "1 onion, chopped",
      "1 green bell pepper, chopped",
      "1 can (10 oz) diced tomatoes with green chiles",
      "1 can (10.5 oz) cream of chicken soup",
      "1 cup sour cream",
      "2 teaspoons chili powder",
      "1 teaspoon ground cumin",
      "12 corn tortillas, torn",
      "3 cups shredded cheddar and Monterey Jack",
      "Chopped cilantro"
    ],
    steps: [
      "Heat the oven to 375°F. Soften the onion and pepper in a little oil.",
      "Stir in the tomatoes, soup, sour cream, chili powder, and cumin. Fold in the chicken.",
      "Layer half the tortillas, half the chicken sauce, and a third of the cheese in a buttered 9-by-13-inch pan. Repeat.",
      "Finish with the remaining cheese. Bake 35–40 minutes until bubbling and spotted brown.",
      "Rest 10 minutes, then scatter cilantro and cut squares."
    ],
    image: "/images/king-ranch.jpg",
    imageCredit: commons,
    sourceUrl: "https://en.wikipedia.org/wiki/King_Ranch_Chicken",
    sourceTitle: "King Ranch chicken"
  },
  {
    id: "breakfast-tacos",
    title: "Texas Breakfast Tacos",
    cuisine: "texas",
    category: "Breakfast",
    summary: "Flour tortillas, scrambled eggs, crisp potato, and cheese. The breakfast that comes in a paper sleeve.",
    yieldText: "4 tacos",
    prepMinutes: 10,
    cookMinutes: 20,
    ingredients: [
      "4 flour tortillas",
      "2 medium russet potatoes, diced small",
      "4 large eggs",
      "1 tablespoon butter",
      "1/2 cup shredded cheddar",
      "Kosher salt and black pepper",
      "Salsa roja",
      "Oil for the potatoes"
    ],
    steps: [
      "Fry the potatoes in a slick of oil over medium heat until golden and tender. Salt them.",
      "Beat the eggs with a pinch of salt. Scramble them gently in the butter until just set.",
      "Warm the tortillas in a dry skillet.",
      "Fill each tortilla with potato, egg, and cheese.",
      "Add salsa at the table so the tortilla stays soft."
    ],
    image: "/images/tacos.jpg",
    imageCredit: book,
    sourceUrl: "https://en.wikipedia.org/wiki/Breakfast_taco",
    sourceTitle: "Breakfast taco"
  },
  {
    id: "chile-con-queso",
    title: "Chile con Queso",
    cuisine: "texas",
    category: "Sides",
    summary: "A bowl of warm cheese with green chile and a little tomato, made for tortilla chips and for staying on the stove.",
    yieldText: "About 3 cups",
    prepMinutes: 10,
    cookMinutes: 15,
    ingredients: [
      "1 tablespoon butter",
      "1/2 onion, minced",
      "1 jalapeño, minced",
      "1 can (4 oz) diced green chiles",
      "1 small tomato, seeded and diced",
      "1 tablespoon cornstarch",
      "1 cup evaporated milk",
      "12 oz white American or Monterey Jack, shredded",
      "Tortilla chips"
    ],
    steps: [
      "Melt the butter and soften the onion and jalapeño.",
      "Stir in the green chiles and tomato.",
      "Whisk the cornstarch into the evaporated milk and pour it in. Simmer until slightly thick.",
      "Lower the heat and stir in the cheese a handful at a time until smooth.",
      "Keep it warm and serve with chips. If it tightens, loosen it with a splash of milk."
    ],
    image: "/images/queso.jpg",
    imageCredit: commons,
    sourceUrl: "https://en.wikipedia.org/wiki/Chile_con_queso",
    sourceTitle: "Chile con queso"
  },
  {
    id: "collard-greens",
    title: "Southern Texas Collard Greens",
    cuisine: "texas",
    category: "Sides",
    family: true,
    summary: "A smoky, savory Texas twist on classic greens with brisket or sausage, jalapeño, and a Worcestershire potlikker. Scaled for a 12 oz bag.",
    yieldText: "2–3 servings",
    prepMinutes: 5,
    cookMinutes: 25,
    ingredients: [
      "12 oz frozen chopped collard greens",
      "1/3 cup smoked brisket, chopped, or 3 oz smoked Texas sausage sliced into rounds",
      "1/3 cup yellow onion, diced",
      "1 small jalapeño, seeded and minced",
      "1 small clove garlic, minced",
      "1 1/2 cups beef broth or chicken broth",
      "2 teaspoons butter",
      "1 teaspoon Worcestershire sauce",
      "3/4 teaspoon apple cider vinegar",
      "1/3 teaspoon sugar",
      "1/2 teaspoon seasoned salt",
      "1/2 teaspoon coarse black pepper",
      "1/4 teaspoon garlic powder"
    ],
    steps: [
      "Melt the butter in a medium pot over medium heat. Add the brisket or sausage, onion, and jalapeño. Sauté 3 to 4 minutes until the onion is soft and the meat releases its smoky oils.",
      "Stir in the garlic and cook 1 minute.",
      "Pour in the broth and Worcestershire. Stir in the vinegar, sugar, seasoned salt, pepper, and garlic powder. Bring it to a boil.",
      "Add the frozen greens and stir them into the meat and onion.",
      "Cover and simmer on medium-low 20 to 25 minutes, stirring now and then, until the greens are tender and full of potlikker."
    ],
    notes: "From Tex's kitchen, kept as written.",
    image: "/images/greens.jpg",
    imageCredit: book,
    sourceUrl: "https://en.wikipedia.org/wiki/Collard_(plant)",
    sourceTitle: "Collard greens"
  },
  {
    id: "bbq-chicken-thighs",
    title: "Hot Honey Garlic BBQ Chicken Thighs",
    cuisine: "texas",
    category: "Mains",
    family: true,
    summary: "Boneless thighs in a sweet garlic marinade, packed in a gallon bag so the flavor gets all the way through.",
    yieldText: "3.18 lb chicken",
    prepMinutes: 15,
    cookMinutes: 30,
    ingredients: [
      "3.18 lb boneless, skinless chicken thighs",
      "1 cup Kinder's Hot Honey BBQ marinade",
      "2 tablespoons minced garlic",
      "1 tablespoon Cowboy Butter with Jalapeño seasoning",
      "1 teaspoon Slap Ya Mama Cajun seasoning",
      "1 teaspoon coarse black pepper",
      "1/2 teaspoon sea salt",
      "1 gallon freezer bag"
    ],
    steps: [
      "Pat the thighs dry. Put them in the freezer bag with the garlic, Cowboy Butter seasoning, Slap Ya Mama, pepper, and salt.",
      "Pour in the marinade. Press out the air, seal, and massage the bag. Refrigerate at least 2 hours, or overnight.",
      "Grill or pan-sear over medium-high heat 6 to 8 minutes a side, brushing with a little marinade near the end, until the center reaches 175°F.",
      "Or bake at 400°F on a lined sheet for 25 to 30 minutes, until the edges char.",
      "Rest 5 minutes before slicing."
    ],
    notes: "From Tex's kitchen, kept as written. The marinate time is the real cook time.",
    image: "/images/bbq-chicken.jpg",
    imageCredit: commons,
    sourceUrl: "https://en.wikipedia.org/wiki/Barbecue_chicken",
    sourceTitle: "Barbecue chicken"
  },
  {
    id: "jasmine-rice-and-beans",
    title: "Jasmine Rice and Red Beans",
    cuisine: "texas",
    category: "Sides",
    family: true,
    summary: "A rice-cooker side built for a Roma pot: rinsed jasmine rice, kidney beans, and broth instead of water.",
    yieldText: "4–6 servings",
    prepMinutes: 5,
    cookMinutes: 25,
    ingredients: [
      "2 cups long-grain jasmine rice, rinsed",
      "1 can (15 oz) light red kidney beans, drained and rinsed",
      "2 1/2 cups beef or chicken broth",
      "1 tablespoon butter or olive oil",
      "1 teaspoon garlic powder",
      "1/2 teaspoon onion powder",
      "1/2 teaspoon coarse black pepper",
      "A pinch of sea salt"
    ],
    steps: [
      "Rinse the rice until the water runs mostly clear. Drain it into the rice-cooker pot.",
      "Add the beans, broth, butter, and spices. Swirl once.",
      "Close the lid and set the cooker to Cook.",
      "When it flips to Warm, leave the lid shut another 10 minutes.",
      "Fluff with a fork and serve beside chicken or greens."
    ],
    notes: "From Tex's kitchen. Use the cup that came with the Roma cooker when you can, or keep this 1-to-1.25 liquid ratio.",
    image: "/images/rice-beans.jpg",
    imageCredit: book,
    sourceUrl: "https://en.wikipedia.org/wiki/Rice_and_beans",
    sourceTitle: "Rice and beans"
  },
  {
    id: "raspberry-sweet-tea",
    title: "Lone Star Raspberry Sweet Tea",
    cuisine: "texas",
    category: "Drinks",
    family: true,
    summary: "A gallon of iced tea sweetened while it is hot, stained with real raspberry syrup.",
    yieldText: "1 gallon",
    prepMinutes: 10,
    cookMinutes: 20,
    ingredients: [
      "3 quarts water, divided",
      "6–8 family-size black tea bags, Luzianne or Lipton",
      "1 to 1 1/2 cups sugar",
      "6 oz fresh or frozen raspberries",
      "1 pinch baking soda",
      "Ice and lemon, for serving"
    ],
    steps: [
      "Boil 4 cups of water. Take it off the heat, add the tea bags and a pinch of baking soda, cover, and steep 15 minutes.",
      "Discard the bags without squeezing them. Stir the sugar into the hot tea until it dissolves.",
      "Simmer the raspberries with 1/2 cup water and 2 tablespoons sugar for 5 minutes, crushing them. Strain out the seeds and stir the syrup into the tea.",
      "Pour into a gallon pitcher and fill with cold water, about 7 to 8 cups more.",
      "Chill at least 2 hours. Serve over ice with lemon or extra berries."
    ],
    notes: "From Tex's kitchen, kept as written.",
    image: "/images/tea.jpg",
    imageCredit: book,
    sourceUrl: "https://en.wikipedia.org/wiki/Sweet_tea",
    sourceTitle: "Sweet tea"
  },
  {
    id: "texas-sheet-cake",
    title: "Texas Sheet Cake",
    cuisine: "texas",
    category: "Sweets",
    summary: "A thin chocolate cake baked in a jelly-roll pan and flooded, while both are hot, with a pecan fudge icing.",
    yieldText: "24 squares",
    prepMinutes: 20,
    cookMinutes: 20,
    ingredients: [
      "2 cups flour",
      "2 cups sugar",
      "1 teaspoon baking soda",
      "1/2 teaspoon salt",
      "1 cup butter",
      "1/4 cup cocoa powder",
      "1 cup water",
      "1/2 cup buttermilk",
      "2 eggs",
      "1 teaspoon vanilla",
      "For the icing: 1/2 cup butter, 1/4 cup cocoa, 6 tablespoons milk, 3 1/2 cups powdered sugar, 1 teaspoon vanilla, 1 cup toasted pecans"
    ],
    steps: [
      "Heat the oven to 350°F. Butter a 13-by-18-inch sheet pan.",
      "Whisk the flour, sugar, soda, and salt. Boil 1 cup butter, the cocoa, and water, then pour it over the dry ingredients.",
      "Beat in the buttermilk, eggs, and vanilla. Spread the thin batter in the pan and bake 18–20 minutes.",
      "While it bakes, boil the icing butter, cocoa, and milk. Beat in the powdered sugar and vanilla, then the pecans.",
      "Pour the hot icing over the hot cake and spread it to the edges. Cool before cutting."
    ],
    image: "/images/sheet-cake.jpg",
    imageCredit: book,
    sourceUrl: "https://en.wikipedia.org/wiki/Sheet_cake",
    sourceTitle: "Sheet cake"
  },
  {
    id: "pecan-pie",
    title: "Texas Pecan Pie",
    cuisine: "texas",
    category: "Sweets",
    summary: "A deep custard of pecans, brown sugar, and a little corn syrup in a plain butter crust.",
    yieldText: "8 slices",
    prepMinutes: 20,
    cookMinutes: 55,
    ingredients: [
      "1 unbaked 9-inch pie crust",
      "1 1/2 cups pecan halves",
      "3 large eggs",
      "1 cup packed brown sugar",
      "3/4 cup light corn syrup",
      "1/4 cup butter, melted",
      "1 teaspoon vanilla",
      "1/4 teaspoon salt"
    ],
    steps: [
      "Heat the oven to 350°F. Spread the pecans in the crust.",
      "Whisk the eggs, brown sugar, syrup, butter, vanilla, and salt until smooth.",
      "Pour the custard over the pecans.",
      "Bake 50–55 minutes, until the center barely wobbles. Shield the crust if it browns too fast.",
      "Cool completely before slicing. The filling finishes setting as it cools."
    ],
    image: "/images/pecan-pie.jpg",
    imageCredit: commons,
    sourceUrl: "https://en.wikipedia.org/wiki/Pecan_pie",
    sourceTitle: "Pecan pie"
  },
  {
    id: "skillet-cornbread",
    title: "Skillet Cornbread",
    cuisine: "texas",
    category: "Sides",
    summary: "A hot iron skillet, yellow cornmeal, and buttermilk. No sugar, the way it belongs next to beans and greens.",
    yieldText: "8 wedges",
    prepMinutes: 10,
    cookMinutes: 25,
    ingredients: [
      "1 1/2 cups yellow cornmeal",
      "1/2 cup all-purpose flour",
      "1 teaspoon kosher salt",
      "1 teaspoon baking powder",
      "1/2 teaspoon baking soda",
      "1 1/2 cups buttermilk",
      "2 eggs",
      "1/4 cup bacon drippings or butter, divided"
    ],
    steps: [
      "Heat the oven to 425°F. Put a 10-inch cast-iron skillet inside with 2 tablespoons drippings.",
      "Whisk the cornmeal, flour, salt, baking powder, and soda.",
      "Stir in the buttermilk, eggs, and remaining melted drippings.",
      "Pour the batter into the hot skillet. It should sizzle.",
      "Bake 20–25 minutes until the top is browned and the center is set."
    ],
    image: "/images/cornbread.jpg",
    imageCredit: book,
    sourceUrl: "https://en.wikipedia.org/wiki/Cornbread",
    sourceTitle: "Cornbread"
  },
  {
    id: "charro-beans",
    title: "Frijoles Charros",
    cuisine: "texas",
    category: "Sides",
    summary: "Pinto beans cooked with bacon, tomato, and jalapeño until the broth is worth spooning on its own.",
    yieldText: "8 servings",
    prepMinutes: 15,
    cookMinutes: 120,
    ingredients: [
      "1 lb dried pinto beans, rinsed",
      "6 cups water",
      "6 oz bacon, chopped",
      "1 onion, chopped",
      "3 garlic cloves, minced",
      "1 jalapeño, sliced",
      "1 large tomato, chopped",
      "1 teaspoon ground cumin",
      "1 teaspoon kosher salt",
      "1/4 cup chopped cilantro"
    ],
    steps: [
      "Cover the beans with water and simmer while you cook the bacon.",
      "Render the bacon, then soften the onion, garlic, and jalapeño in the drippings.",
      "Add the tomato and cumin and cook until the tomato slumps.",
      "Scrape everything into the beans. Simmer 1 1/2 to 2 hours, adding water if they look dry, until the beans are creamy.",
      "Salt at the end and stir in the cilantro."
    ],
    image: "/images/charro.jpg",
    imageCredit: book,
    sourceUrl: "https://en.wikipedia.org/wiki/Frijoles_charros",
    sourceTitle: "Frijoles charros"
  },
  {
    id: "chicken-sausage-gumbo",
    title: "Chicken and Sausage Gumbo",
    cuisine: "cajun",
    category: "Mains",
    summary: "A dark roux, andouille, chicken, and okra, ladled beside a mound of rice.",
    yieldText: "8 servings",
    prepMinutes: 30,
    cookMinutes: 90,
    ingredients: [
      "3/4 cup oil",
      "3/4 cup flour",
      "1 lb andouille, sliced",
      "2 lb bone-in chicken thighs",
      "1 onion, 1 bell pepper, and 2 celery stalks, chopped",
      "6 garlic cloves, minced",
      "8 cups chicken stock",
      "1 tablespoon Cajun seasoning",
      "2 bay leaves",
      "2 cups sliced okra",
      "Cooked white rice and green onion"
    ],
    steps: [
      "Brown the sausage and chicken in a heavy pot. Set them aside.",
      "Stir the oil and flour over medium heat until the roux is the color of a copper penny, 20–30 minutes. Do not walk away.",
      "Throw in the onion, pepper, and celery. Cook until soft, then add the garlic.",
      "Whisk in the stock. Return the meats, seasoning, and bay. Simmer 45 minutes.",
      "Add the okra and cook 15 minutes more. Pull out the bones, adjust the salt, and serve beside rice with green onion."
    ],
    notes: "If the roux smells burnt, start it over. There is no saving a scorched one.",
    image: "/images/gumbo.jpg",
    imageCredit: book,
    sourceUrl: "https://en.wikipedia.org/wiki/Gumbo",
    sourceTitle: "Gumbo"
  },
  {
    id: "seafood-gumbo",
    title: "Seafood Gumbo",
    cuisine: "cajun",
    category: "Mains",
    summary: "Shrimp and sausage in a tomato-tinted pot, finished with green onion and served with rice.",
    yieldText: "8 servings",
    prepMinutes: 25,
    cookMinutes: 70,
    ingredients: [
      "1/2 cup oil",
      "1/2 cup flour",
      "12 oz smoked sausage, sliced",
      "1 onion, 1 bell pepper, and 2 celery stalks, chopped",
      "4 garlic cloves, minced",
      "1 can (14 oz) diced tomatoes",
      "6 cups seafood or chicken stock",
      "1 1/2 lb shrimp, peeled",
      "1 tablespoon Creole seasoning",
      "Cooked rice, green onion, and French bread"
    ],
    steps: [
      "Cook the oil and flour to a peanut-butter roux.",
      "Add the sausage and vegetables and cook until the vegetables soften.",
      "Stir in the garlic, tomatoes, stock, and seasoning. Simmer 40 minutes.",
      "Add the shrimp and cook just until they turn pink, about 4 minutes.",
      "Serve over rice with green onion and bread for the bowl."
    ],
    image: "/images/seafood-gumbo.jpg",
    imageCredit: commons,
    sourceUrl: "https://en.wikipedia.org/wiki/Gumbo",
    sourceTitle: "Gumbo"
  },
  {
    id: "creole-shrimp-jambalaya",
    title: "Creole Shrimp Jambalaya",
    cuisine: "cajun",
    category: "Mains",
    summary: "Rice cooked in the same pot as shrimp, tomato, and a little smoked pork, the red New Orleans way.",
    yieldText: "8 servings",
    prepMinutes: 20,
    cookMinutes: 45,
    ingredients: [
      "2 tablespoons oil",
      "8 oz tasso or smoked ham, diced",
      "1 onion, 1 green pepper, and 2 celery stalks, chopped",
      "4 garlic cloves, minced",
      "1 can (14 oz) crushed tomatoes",
      "2 teaspoons Creole seasoning",
      "1 teaspoon thyme",
      "2 cups long-grain rice",
      "3 1/2 cups chicken stock",
      "1 1/2 lb shrimp, peeled",
      "Green onion"
    ],
    steps: [
      "Brown the ham in the oil. Add the trinity and cook until soft.",
      "Stir in the garlic, tomatoes, seasoning, and thyme.",
      "Add the rice and stock. Bring to a boil, cover, and simmer 18 minutes.",
      "Lay the shrimp on top, cover again, and cook 6 minutes.",
      "Fold everything together and finish with green onion."
    ],
    image: "/images/jambalaya.jpg",
    imageCredit: commons,
    sourceUrl: "https://en.wikipedia.org/wiki/Jambalaya",
    sourceTitle: "Jambalaya"
  },
  {
    id: "crawfish-etouffee",
    title: "Crawfish Étouffée",
    cuisine: "cajun",
    category: "Mains",
    summary: "Crawfish tails smothered in a butter roux with the trinity, spooned around a hill of rice.",
    yieldText: "6 servings",
    prepMinutes: 20,
    cookMinutes: 40,
    ingredients: [
      "1/2 cup butter",
      "1/3 cup flour",
      "1 onion, 1 bell pepper, and 2 celery stalks, finely chopped",
      "4 garlic cloves, minced",
      "1 1/2 cups seafood stock",
      "1 lb crawfish tails with any fat",
      "1 teaspoon Cajun seasoning",
      "1/2 teaspoon cayenne, or to taste",
      "2 green onions, sliced",
      "Cooked rice"
    ],
    steps: [
      "Melt the butter and stir in the flour. Cook to a blond roux, just past raw.",
      "Add the trinity and cook until soft, then the garlic.",
      "Whisk in the stock and simmer 15 minutes until it can coat a spoon.",
      "Stir in the crawfish, seasoning, and cayenne. Simmer 8 minutes. Do not boil hard or the tails toughen.",
      "Fold in the green onion and serve around rice."
    ],
    image: "/images/etouffee.jpg",
    imageCredit: commons,
    sourceUrl: "https://en.wikipedia.org/wiki/%C3%89touff%C3%A9e",
    sourceTitle: "Étouffée"
  },
  {
    id: "red-beans-and-rice",
    title: "Monday Red Beans and Rice",
    cuisine: "cajun",
    category: "Mains",
    summary: "Creamy red beans cooked with a leftover ham bone, spooned over rice the way Mondays were meant to go.",
    yieldText: "8 servings",
    prepMinutes: 20,
    cookMinutes: 150,
    ingredients: [
      "1 lb dried red kidney beans, soaked overnight",
      "1 leftover ham bone or 8 oz pickled pork",
      "1 onion, 1 bell pepper, and 2 celery stalks, chopped",
      "6 garlic cloves, minced",
      "2 bay leaves",
      "1 teaspoon thyme",
      "1/2 teaspoon cayenne",
      "8 cups water",
      "Cooked rice and green onion",
      "Hot sauce"
    ],
    steps: [
      "Drain the beans into a heavy pot with the ham bone and water.",
      "Add the vegetables, garlic, bay, thyme, and cayenne.",
      "Simmer gently 2 to 2 1/2 hours, stirring more often near the end so nothing catches.",
      "Mash a cup of beans against the pot wall and stir them back in to cream the broth. Salt only after the beans are soft.",
      "Serve over rice with green onion and hot sauce. Pick the meat off the bone."
    ],
    image: "/images/red-beans.jpg",
    imageCredit: commons,
    sourceUrl: "https://en.wikipedia.org/wiki/Red_beans_and_rice",
    sourceTitle: "Red beans and rice"
  },
  {
    id: "dirty-rice",
    title: "Dirty Rice",
    cuisine: "cajun",
    category: "Sides",
    summary: "Rice stained with chicken liver, pork, and the trinity. It is a side that can stand as supper.",
    yieldText: "6 servings",
    prepMinutes: 15,
    cookMinutes: 35,
    ingredients: [
      "1/2 lb ground pork",
      "1/4 lb chicken livers, finely chopped",
      "1 onion, 1 bell pepper, and 1 celery stalk, minced",
      "3 garlic cloves, minced",
      "1 teaspoon Cajun seasoning",
      "3 cups cooked long-grain rice",
      "1 cup chicken stock",
      "2 green onions"
    ],
    steps: [
      "Brown the pork in a skillet, breaking it fine.",
      "Add the livers and cook until they lose their pink.",
      "Add the trinity and garlic and cook until soft. Season.",
      "Fold in the rice and splash in stock until the rice is moist, not soupy.",
      "Finish with green onion."
    ],
    image: "/images/dirty-rice.jpg",
    imageCredit: commons,
    sourceUrl: "https://en.wikipedia.org/wiki/Dirty_rice",
    sourceTitle: "Dirty rice"
  },
  {
    id: "blackened-catfish",
    title: "Blackened Catfish",
    cuisine: "cajun",
    category: "Mains",
    summary: "A spiced fillet seared in a ripping-hot iron skillet until the crust is dark and the center is still moist.",
    yieldText: "4 fillets",
    prepMinutes: 10,
    cookMinutes: 10,
    ingredients: [
      "4 catfish fillets",
      "4 tablespoons butter, melted",
      "2 teaspoons paprika",
      "1 teaspoon kosher salt",
      "1 teaspoon garlic powder",
      "1 teaspoon onion powder",
      "1 teaspoon dried thyme",
      "1 teaspoon dried oregano",
      "1/2 teaspoon cayenne",
      "1 teaspoon black pepper",
      "Lemon wedges"
    ],
    steps: [
      "Heat a cast-iron skillet over high heat until it barely smokes. Open a window.",
      "Mix the spices. Brush the fillets with butter and press the spice on both sides.",
      "Lay the fish in the dry hot skillet. Cook about 2–3 minutes, until a dark crust forms.",
      "Turn once and cook until the thickest part flakes.",
      "Serve with lemon. The butter in the spice is the sauce."
    ],
    image: "/images/blackened-catfish.jpg",
    imageCredit: commons,
    sourceUrl: "https://en.wikipedia.org/wiki/Blackening_(cooking)",
    sourceTitle: "Blackening"
  },
  {
    id: "shrimp-creole",
    title: "Shrimp Creole",
    cuisine: "cajun",
    category: "Mains",
    summary: "Shrimp simmered briefly in a peppery tomato sauce and settled into a ring of rice.",
    yieldText: "6 servings",
    prepMinutes: 20,
    cookMinutes: 40,
    ingredients: [
      "2 tablespoons butter",
      "1 onion, 1 green pepper, and 1 celery stalk, chopped",
      "3 garlic cloves, minced",
      "1 can (28 oz) crushed tomatoes",
      "1 bay leaf",
      "1 teaspoon Creole seasoning",
      "1/2 teaspoon thyme",
      "1 1/2 lb shrimp, peeled",
      "1 teaspoon Worcestershire sauce",
      "Cooked rice"
    ],
    steps: [
      "Soften the onion, pepper, and celery in the butter.",
      "Add the garlic, tomatoes, bay, seasoning, and thyme. Simmer 25 minutes.",
      "Stir in the shrimp and Worcestershire.",
      "Cook 4 minutes, until the shrimp are just pink. Pull the bay leaf.",
      "Spoon into a ring of rice."
    ],
    image: "/images/shrimp-creole.jpg",
    imageCredit: commons,
    sourceUrl: "https://en.wikipedia.org/wiki/Shrimp_creole",
    sourceTitle: "Shrimp Creole"
  },
  {
    id: "cajun-boudin",
    title: "Cajun Boudin",
    cuisine: "cajun",
    category: "Mains",
    summary: "Pork and rice, highly seasoned, stuffed into casings. Slice it hot and eat it with crackers if the drive is long.",
    yieldText: "About 3 lb",
    prepMinutes: 40,
    cookMinutes: 90,
    ingredients: [
      "2 lb pork shoulder",
      "1/2 lb pork liver",
      "1 onion, chopped",
      "1 green onion bunch",
      "3 garlic cloves",
      "2 tablespoons Cajun seasoning",
      "1 teaspoon cayenne",
      "3 cups cooked rice",
      "1/2 cup chopped parsley",
      "Sausage casings, rinsed"
    ],
    steps: [
      "Cover the shoulder, liver, onion, and garlic with water. Simmer until the pork is tender, about 1 hour.",
      "Reserve 1 cup of the broth. Grind or finely chop the meats and cooked onion.",
      "Mix with the rice, green onion, parsley, seasoning, cayenne, and enough broth to make a moist stuffing.",
      "Stuff loosely into casings. Poach 15 minutes or grill over medium heat until heated through and spotted.",
      "Slice and serve hot. The rice should look moist, never dry."
    ],
    image: "/images/boudin.jpg",
    imageCredit: book,
    sourceUrl: "https://en.wikipedia.org/wiki/Boudin",
    sourceTitle: "Boudin"
  },
  {
    id: "beignets",
    title: "New Orleans Beignets",
    cuisine: "cajun",
    category: "Sweets",
    summary: "Pillows of yeast dough fried and buried under powdered sugar.",
    yieldText: "About 24",
    prepMinutes: 20,
    cookMinutes: 20,
    ingredients: [
      "1 cup warm milk",
      "2 1/4 teaspoons active dry yeast",
      "1/4 cup sugar",
      "1 egg",
      "3 tablespoons melted butter",
      "3 cups flour",
      "1/2 teaspoon salt",
      "Oil for frying",
      "Powdered sugar"
    ],
    steps: [
      "Stir the yeast into the warm milk with a pinch of the sugar. Let it foam.",
      "Beat in the remaining sugar, egg, and butter. Add the flour and salt and knead into a soft dough.",
      "Rise, covered, about 1 hour. Roll 1/4 inch thick and cut squares.",
      "Fry at 360°F until puffed and golden, turning once.",
      "Drain for a moment and shower with powdered sugar while they are hot."
    ],
    image: "/images/beignets.jpg",
    imageCredit: book,
    sourceUrl: "https://en.wikipedia.org/wiki/Beignet",
    sourceTitle: "Beignet"
  },
  {
    id: "bread-pudding",
    title: "New Orleans Bread Pudding",
    cuisine: "cajun",
    category: "Sweets",
    summary: "Stale French bread baked in custard with raisins, then finished with a warm butter sauce.",
    yieldText: "10 servings",
    prepMinutes: 20,
    cookMinutes: 50,
    ingredients: [
      "8 cups torn day-old French bread",
      "4 cups whole milk",
      "3 eggs",
      "1 1/2 cups sugar",
      "2 teaspoons vanilla",
      "1 teaspoon cinnamon",
      "1/2 cup raisins",
      "1/4 cup melted butter",
      "For the sauce: 1/2 cup butter, 1 cup sugar, 1 egg yolk, 1/4 cup bourbon or milk"
    ],
    steps: [
      "Heat the oven to 350°F. Soak the bread in the milk for 10 minutes.",
      "Whisk the eggs, sugar, vanilla, and cinnamon. Fold into the bread with the raisins and butter.",
      "Bake in a buttered dish 45–50 minutes until the center is set.",
      "For the sauce, melt the butter and sugar, whisk in the yolk off the heat, then the bourbon.",
      "Serve the pudding warm with the sauce."
    ],
    image: "/images/bread-pudding.jpg",
    imageCredit: commons,
    sourceUrl: "https://en.wikipedia.org/wiki/Bread_pudding",
    sourceTitle: "Bread pudding"
  },
  {
    id: "maque-choux",
    title: "Maque Choux",
    cuisine: "cajun",
    category: "Sides",
    summary: "Sweet corn smothered with bell pepper, onion, and tomato until it turns creamy.",
    yieldText: "6 servings",
    prepMinutes: 15,
    cookMinutes: 30,
    ingredients: [
      "4 cups fresh or frozen corn",
      "2 tablespoons butter",
      "1 onion, chopped",
      "1 red bell pepper, diced",
      "2 garlic cloves, minced",
      "1 large tomato, chopped",
      "1/2 cup cream or evaporated milk",
      "1 teaspoon kosher salt",
      "1/2 teaspoon cayenne",
      "2 green onions"
    ],
    steps: [
      "Melt the butter and soften the onion and pepper.",
      "Add the corn and cook until it smells sweet, about 8 minutes.",
      "Stir in the garlic, tomato, salt, and cayenne.",
      "Pour in the cream and simmer until the corn is glossy and the sauce is thick.",
      "Finish with green onion."
    ],
    image: "/images/maque-choux.jpg",
    imageCredit: book,
    sourceUrl: "https://en.wikipedia.org/wiki/Maque_choux",
    sourceTitle: "Maque choux"
  },
  {
    id: "grillades-and-grits",
    title: "Grillades and Grits",
    cuisine: "cajun",
    category: "Breakfast",
    summary: "Thin pork medallions braised in a tomato gravy and laid over creamy grits. A slow Sunday morning.",
    yieldText: "6 servings",
    prepMinutes: 25,
    cookMinutes: 80,
    ingredients: [
      "2 lb pork shoulder, sliced thin",
      "1/2 cup flour",
      "Kosher salt, pepper, and cayenne",
      "3 tablespoons oil",
      "1 onion, 1 bell pepper, and 2 celery stalks, chopped",
      "4 garlic cloves, minced",
      "1 can (14 oz) crushed tomatoes",
      "2 cups beef broth",
      "1 teaspoon thyme",
      "2 cups grits, cooked with milk and butter"
    ],
    steps: [
      "Season the pork and dust it with flour. Brown it in the oil and set it aside.",
      "Cook the trinity in the drippings until soft. Add the garlic.",
      "Stir in the tomatoes, broth, and thyme. Return the pork.",
      "Cover and braise on low for about 1 hour, until the meat is tender and the gravy is thick.",
      "Cook the grits soft and loose. Spoon the grillades over them."
    ],
    image: "/images/grillades.jpg",
    imageCredit: book,
    sourceUrl: "https://en.wikipedia.org/wiki/Grillades",
    sourceTitle: "Grillades"
  },
  {
    id: "hushpuppies",
    title: "Gulf Hushpuppies",
    cuisine: "cajun",
    category: "Sides",
    summary: "Cornmeal fritters fried crisp outside and soft inside, the right company for fish.",
    yieldText: "About 18",
    prepMinutes: 10,
    cookMinutes: 15,
    ingredients: [
      "1 1/2 cups yellow cornmeal",
      "1/2 cup flour",
      "1 tablespoon sugar",
      "2 teaspoons baking powder",
      "1 teaspoon salt",
      "1/2 teaspoon cayenne",
      "1 egg",
      "1 cup buttermilk",
      "3 green onions, sliced",
      "Oil for frying"
    ],
    steps: [
      "Whisk the dry ingredients.",
      "Stir in the egg, buttermilk, and green onion. The batter should be thick.",
      "Heat 2 inches of oil to 360°F.",
      "Drop the batter by the spoonful and fry until deep golden, turning once.",
      "Drain and salt while hot."
    ],
    image: "/images/hushpuppies.jpg",
    imageCredit: commons,
    sourceUrl: "https://en.wikipedia.org/wiki/Hushpuppy",
    sourceTitle: "Hushpuppy"
  },
  {
    id: "courtbouillon",
    title: "Catfish Courtbouillon",
    cuisine: "cajun",
    category: "Mains",
    summary: "A tomato fish stew from the bayou, thick enough to sit on rice, fragrant with thyme and a dark little roux.",
    yieldText: "6 servings",
    prepMinutes: 25,
    cookMinutes: 50,
    ingredients: [
      "1/4 cup oil",
      "1/4 cup flour",
      "1 onion, 1 bell pepper, and 2 celery stalks, chopped",
      "4 garlic cloves, minced",
      "1 can (28 oz) crushed tomatoes",
      "2 cups fish or chicken stock",
      "2 bay leaves",
      "1 teaspoon thyme",
      "2 lb catfish fillets, cut in pieces",
      "Cooked rice and parsley"
    ],
    steps: [
      "Cook the oil and flour to a medium-brown roux.",
      "Add the trinity and cook until soft, then the garlic.",
      "Stir in the tomatoes, stock, bay, and thyme. Simmer 25 minutes.",
      "Nestle in the fish, cover, and cook 10 minutes until it flakes.",
      "Serve over rice with parsley. Do not stir hard or the fish will break."
    ],
    image: "/images/courtbouillon.jpg",
    imageCredit: book,
    sourceUrl: "https://en.wikipedia.org/wiki/Court-bouillon",
    sourceTitle: "Court-bouillon"
  }
];

export const RECIPES = [...BOOK, ...STAPLES, ...MORE];
