const nchfp = "https://nchfp.uga.edu/how/can/canning-vegetables-and-vegetable-products/beans-snap-and-italian-pieces-green-and-wax/";

export const STAPLES = [
  {
    id: "beef-fajitas",
    title: "Beef Fajitas",
    cuisine: "texmex",
    category: "Mains",
    summary: "Skirt steak sliced thin against the grain, with charred onion and bell pepper, piled into warm flour tortillas. This is the South Texas skillet.",
    yieldText: "6 servings",
    prepMinutes: 25,
    cookMinutes: 20,
    ingredients: [
      "2 lb skirt or flank steak",
      "1/4 cup lime juice",
      "3 tablespoons oil, divided",
      "3 garlic cloves, minced",
      "2 teaspoons chili powder",
      "2 teaspoons ground cumin",
      "1 teaspoon kosher salt",
      "1 teaspoon black pepper",
      "2 bell peppers, sliced",
      "1 large onion, sliced",
      "Warm flour tortillas, salsa, cilantro, and lime"
    ],
    steps: [
      "Trim the steak and cut it with the grain into pieces that fit the skillet. Toss with the lime juice, 1 tablespoon oil, garlic, chili powder, cumin, salt, and pepper. Rest 20 minutes.",
      "Heat a heavy skillet until it smokes. Sear the steak 2 to 3 minutes a side for medium. Rest it 5 minutes, then slice thin against the grain.",
      "In the same skillet, cook the onion and peppers in the remaining oil until the edges char and the onion sweetens.",
      "Serve the meat and vegetables on warm tortillas. Pass salsa, cilantro, and lime."
    ],
    notes: "A screaming-hot pan matters more than a long marinade. Slice only after the rest, or the juices run out.",
    image: "/images/beef-fajitas.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "https://en.wikipedia.org/wiki/Fajita",
    sourceTitle: "Fajita",
    youtube: "",
    family: true
  },
  {
    id: "carne-guisada",
    title: "Carne Guisada",
    cuisine: "texmex",
    category: "Mains",
    summary: "Texas beef stew in a cumin gravy, soft enough to spoon into a flour tortilla.",
    yieldText: "8 servings",
    prepMinutes: 25,
    cookMinutes: 150,
    ingredients: [
      "3 lb beef chuck, cut in 1-inch cubes",
      "2 teaspoons kosher salt",
      "2 tablespoons oil",
      "1 onion, chopped",
      "1 bell pepper, chopped",
      "1 jalapeño, minced",
      "4 garlic cloves, minced",
      "2 tablespoons flour",
      "1 tablespoon ground cumin",
      "2 teaspoons chili powder",
      "1 teaspoon oregano",
      "1 can (10 oz) diced tomatoes with green chiles",
      "2 cups beef broth",
      "Flour tortillas, for serving"
    ],
    steps: [
      "Salt the beef. Brown it in the oil in batches and set it aside.",
      "Cook the onion, bell pepper, and jalapeño in the same pot until soft. Add the garlic, cumin, chili powder, and oregano for 30 seconds.",
      "Stir in the flour, then the tomatoes and broth. Return the beef and any juices.",
      "Cover and simmer gently about 2 hours, until the beef is tender and the gravy is thick. Salt to taste.",
      "Serve in warm flour tortillas, or over rice with beans."
    ],
    notes: "Keep the simmer low. A hard boil makes the meat stringy.",
    image: "/images/carne-guisada.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "cheese-enchiladas",
    title: "Cheese Enchiladas with Chili Gravy",
    cuisine: "texmex",
    category: "Mains",
    summary: "The Texas plate: corn tortillas rolled around cheese and onion, covered in a cumin chili gravy and more cheese.",
    yieldText: "6 servings",
    prepMinutes: 30,
    cookMinutes: 35,
    ingredients: [
      "1/4 cup oil, plus more for softening tortillas",
      "1/4 cup flour",
      "1/4 cup chili powder",
      "2 teaspoons ground cumin",
      "1 teaspoon garlic powder",
      "1 teaspoon oregano",
      "3 cups beef or chicken broth",
      "1 teaspoon kosher salt",
      "12 corn tortillas",
      "3 cups shredded cheddar or a cheddar and jack mix",
      "1 onion, finely chopped"
    ],
    steps: [
      "Heat the oven to 375°F. Whisk the oil and flour in a saucepan for 1 minute. Stir in the chili powder, cumin, garlic powder, and oregano.",
      "Whisk in the broth and salt. Simmer until the gravy coats a spoon, about 8 minutes.",
      "Soften each tortilla in a slick of hot oil for a few seconds a side. Dip it in gravy.",
      "Fill with cheese and onion, roll, and place seam-down in a baking dish. Cover with the rest of the gravy and cheese.",
      "Bake until the cheese is bubbling, about 20 minutes. Rest 5 minutes so the gravy sets."
    ],
    notes: "Texas chili gravy is not a tomato sauce. If it tastes flat, it needs salt, not sugar.",
    image: "/images/cheese-enchiladas.jpg",
    imageCredit: "Wikimedia Commons",
    sourceUrl: "https://en.wikipedia.org/wiki/Enchilada",
    sourceTitle: "Enchilada",
    youtube: "",
    family: true
  },
  {
    id: "beef-enchiladas",
    title: "Beef Enchiladas",
    cuisine: "texmex",
    category: "Mains",
    summary: "Shredded beef rolled in corn tortillas with the same chili gravy used on the cheese plate.",
    yieldText: "8 servings",
    prepMinutes: 30,
    cookMinutes: 40,
    ingredients: [
      "2 lb cooked beef chuck or brisket, shredded",
      "1 onion, chopped, divided",
      "2 cups shredded cheddar",
      "12 corn tortillas",
      "3 cups chili gravy, from the cheese enchilada plate or your own",
      "Oil for softening tortillas",
      "Cilantro, for serving"
    ],
    steps: [
      "Heat the oven to 375°F. Mix the beef with half the onion and 1 cup of the gravy.",
      "Soften the tortillas in a little oil, then dip them in gravy.",
      "Fill with beef and a little cheese, roll, and set them seam-down in a baking dish.",
      "Pour the remaining gravy over the top and scatter the rest of the cheese and onion.",
      "Bake 25 minutes, until bubbling. Scatter cilantro and serve with rice and beans."
    ],
    notes: "Leftover brisket is the right beef for this plate.",
    image: "/images/beef-enchiladas.jpg",
    imageCredit: "Wikimedia Commons",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "carne-asada",
    title: "Carne Asada",
    cuisine: "texmex",
    category: "Mains",
    summary: "Citrus-and-chile flank steak for the grill, sliced for tacos, bowls, or a Sunday platter.",
    yieldText: "8 servings",
    prepMinutes: 20,
    cookMinutes: 15,
    ingredients: [
      "3 lb flank or skirt steak",
      "1/3 cup orange juice",
      "1/4 cup lime juice",
      "3 tablespoons oil",
      "4 garlic cloves, minced",
      "1 jalapeño, minced",
      "2 teaspoons kosher salt",
      "1 tablespoon ground cumin",
      "2 teaspoons chili powder",
      "1 teaspoon black pepper",
      "1/2 cup chopped cilantro",
      "Warm tortillas, onion, and salsa"
    ],
    steps: [
      "Mix the juices, oil, garlic, jalapeño, salt, cumin, chili powder, pepper, and cilantro. Coat the steak and refrigerate 2 to 8 hours.",
      "Grill over a hot fire, about 4 minutes a side for medium-rare on flank. Skirt is faster.",
      "Rest 8 minutes. Slice thin against the grain.",
      "Serve with warm tortillas, chopped onion, cilantro, and salsa."
    ],
    notes: "Take the steak out of the icebox 30 minutes before it hits the fire.",
    image: "/images/carne-asada.jpg",
    imageCredit: "Wikimedia Commons",
    sourceUrl: "https://en.wikipedia.org/wiki/Carne_asada",
    sourceTitle: "Carne asada",
    youtube: "",
    family: true
  },
  {
    id: "texas-ribeye",
    title: "Cast-Iron Ribeye",
    cuisine: "texas",
    category: "Mains",
    summary: "A thick ribeye seared in a hot iron skillet and finished with butter, garlic, and pepper.",
    yieldText: "2 servings",
    prepMinutes: 10,
    cookMinutes: 12,
    ingredients: [
      "2 ribeye steaks, about 1 1/4 inches thick",
      "Kosher salt and coarse black pepper",
      "1 tablespoon oil",
      "2 tablespoons butter",
      "2 garlic cloves, crushed",
      "2 sprigs thyme or a pinch of dried thyme"
    ],
    steps: [
      "Salt the steaks and leave them uncovered in the icebox for an hour if you have it, or 20 minutes on the counter.",
      "Heat a cast-iron skillet until it is very hot. Oil it lightly. Sear the steaks 3 to 4 minutes without moving them.",
      "Turn them. Add the butter, garlic, and thyme. Tilt the pan and spoon the butter over the steaks for 2 to 3 minutes more, to about 130°F for medium-rare.",
      "Rest 5 minutes. Pepper them at the table."
    ],
    notes: "Pepper burns if it goes on before the sear. Add it at the end.",
    image: "/images/texas-ribeye.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "sunday-pot-roast",
    title: "Sunday Beef Pot Roast",
    cuisine: "texas",
    category: "Mains",
    summary: "Chuck roast braised with onion, carrot, and potato until a fork falls through it.",
    yieldText: "8 servings",
    prepMinutes: 25,
    cookMinutes: 210,
    ingredients: [
      "4 lb beef chuck roast",
      "2 teaspoons kosher salt",
      "1 teaspoon black pepper",
      "2 tablespoons oil",
      "1 large onion, cut in wedges",
      "4 garlic cloves, smashed",
      "2 cups beef broth",
      "1 tablespoon Worcestershire sauce",
      "2 bay leaves",
      "1 teaspoon thyme",
      "6 carrots, cut in chunks",
      "6 potatoes, halved"
    ],
    steps: [
      "Heat the oven to 300°F. Salt and pepper the roast. Brown it on all sides in the oil in a heavy pot.",
      "Add the onion and garlic and cook 2 minutes. Pour in the broth and Worcestershire. Add the bay and thyme.",
      "Cover and bake 2 1/2 hours. Tuck in the carrots and potatoes and bake another 45 to 60 minutes, until the beef and potatoes are tender.",
      "Rest 15 minutes. Slice the beef and spoon the broth over the top."
    ],
    notes: "If the broth is thin, simmer it uncovered on the stove for a few minutes after the meat comes out.",
    image: "/images/sunday-pot-roast.jpg",
    imageCredit: "Wikimedia Commons",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "smothered-steak",
    title: "Smothered Steak and Onions",
    cuisine: "texas",
    category: "Mains",
    summary: "Round steak browned hard, then covered with onions and gravy until it gives up.",
    yieldText: "6 servings",
    prepMinutes: 20,
    cookMinutes: 90,
    ingredients: [
      "2 lb round steak, cut in serving pieces",
      "1 teaspoon kosher salt",
      "1 teaspoon black pepper",
      "1/2 cup flour",
      "3 tablespoons oil",
      "2 large onions, sliced",
      "2 cups beef broth",
      "1 teaspoon Worcestershire sauce"
    ],
    steps: [
      "Salt and pepper the steak. Dredge it in flour.",
      "Brown both sides in the oil. Set the steak aside.",
      "Cook the onions in the same skillet until golden. Stir in 2 tablespoons of the leftover flour, then the broth and Worcestershire.",
      "Return the steak, cover, and simmer 75 minutes, until a fork slides in. Add a splash of water if the gravy gets too thick."
    ],
    notes: "Serve with mashed potatoes or rice. The onions are part of the gravy, not a garnish.",
    image: "/images/smothered-steak.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "migas",
    title: "Tex-Mex Migas",
    cuisine: "texmex",
    category: "Breakfast",
    summary: "Scrambled eggs folded with crisp tortilla chips, onion, chile, and cheddar. An Austin morning on a plate.",
    yieldText: "4 servings",
    prepMinutes: 15,
    cookMinutes: 15,
    ingredients: [
      "8 large eggs",
      "1/4 cup milk or cream",
      "1 teaspoon kosher salt",
      "2 tablespoons oil",
      "1/2 onion, chopped",
      "1 jalapeño, minced",
      "1 tomato, chopped",
      "2 cups tortilla chips, lightly crushed",
      "1 cup shredded cheddar",
      "Salsa, cilantro, and warm tortillas"
    ],
    steps: [
      "Beat the eggs with the milk and salt.",
      "Cook the onion and jalapeño in the oil until soft. Add the tomato for 1 minute.",
      "Pour in the eggs and stir gently until they are almost set.",
      "Fold in the chips and cheese. Take the pan off the heat while the eggs are still a little glossy.",
      "Serve at once with salsa and tortillas, while the chips still have some crunch."
    ],
    notes: "Day-old chips work better than fresh ones. They hold their shape.",
    image: "/images/migas.jpg",
    imageCredit: "Wikimedia Commons",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "huevos-rancheros",
    title: "Huevos Rancheros",
    cuisine: "texmex",
    category: "Breakfast",
    summary: "Fried eggs on warm corn tortillas, under a ranchero tomato-chile sauce.",
    yieldText: "4 servings",
    prepMinutes: 15,
    cookMinutes: 25,
    ingredients: [
      "1 tablespoon oil",
      "1/2 onion, chopped",
      "2 garlic cloves, minced",
      "1 jalapeño, minced",
      "1 can (15 oz) crushed tomatoes",
      "1 teaspoon ground cumin",
      "1 teaspoon chili powder",
      "1/2 teaspoon kosher salt",
      "8 corn tortillas",
      "8 eggs",
      "Oil or butter for the eggs",
      "Chopped cilantro and queso fresco or cheddar"
    ],
    steps: [
      "Cook the onion, garlic, and jalapeño in the oil until soft. Add the tomatoes, cumin, chili powder, and salt. Simmer 12 minutes.",
      "Warm the tortillas in a dry skillet and wrap them in a towel.",
      "Fry the eggs in butter or oil the way you like the yolks.",
      "Set two tortillas on each plate, add two eggs, and spoon the sauce over. Finish with cilantro and cheese."
    ],
    notes: "The sauce keeps for three days in the icebox. Make it the night before.",
    image: "/images/huevos-rancheros.jpg",
    imageCredit: "Wikimedia Commons",
    sourceUrl: "https://en.wikipedia.org/wiki/Huevos_rancheros",
    sourceTitle: "Huevos rancheros",
    youtube: "",
    family: true
  },
  {
    id: "biscuits-and-gravy",
    title: "Biscuits and Sausage Gravy",
    cuisine: "texas",
    category: "Breakfast",
    summary: "Hot biscuits split and covered with peppered sausage gravy.",
    yieldText: "6 servings",
    prepMinutes: 20,
    cookMinutes: 25,
    ingredients: [
      "2 cups flour",
      "1 tablespoon baking powder",
      "1 teaspoon kosher salt",
      "1/2 teaspoon black pepper",
      "6 tablespoons cold butter",
      "3/4 cup cold buttermilk",
      "1 lb breakfast sausage",
      "1/4 cup flour, for the gravy",
      "3 cups whole milk",
      "1 teaspoon coarse black pepper, or more"
    ],
    steps: [
      "Heat the oven to 425°F. Stir the flour, baking powder, salt, and 1/2 teaspoon pepper. Cut in the butter until the pieces are pea-sized. Stir in the buttermilk just until a dough forms.",
      "Pat the dough 3/4 inch thick, cut 6 biscuits, and bake about 14 minutes, until risen and golden.",
      "Brown the sausage in a skillet, breaking it up. Stir in the 1/4 cup flour and cook 1 minute.",
      "Whisk in the milk and simmer until the gravy is thick. Season with a heavy hand of pepper and salt if the sausage needs it.",
      "Split the biscuits and ladle the gravy over them."
    ],
    notes: "The gravy should taste like pepper and sausage, not like plain milk.",
    image: "/images/biscuits-and-gravy.jpg",
    imageCredit: "Wikimedia Commons",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "steak-and-eggs",
    title: "Steak and Eggs",
    cuisine: "texas",
    category: "Breakfast",
    summary: "A small steak, eggs fried in the same skillet, and pepper. A ranch breakfast.",
    yieldText: "2 servings",
    prepMinutes: 5,
    cookMinutes: 12,
    ingredients: [
      "2 small steaks, such as sirloin or ribeye tails",
      "Kosher salt and black pepper",
      "1 tablespoon oil",
      "4 eggs",
      "1 tablespoon butter",
      "Toast or biscuits"
    ],
    steps: [
      "Salt the steaks. Sear them in a hot oiled skillet, about 3 minutes a side. Rest them on a plate.",
      "Lower the heat. Melt the butter in the same skillet and fry the eggs in the steak drippings.",
      "Pepper the steak and eggs. Serve with toast or a biscuit."
    ],
    notes: "Do not wash that pan between the steak and the eggs.",
    image: "/images/steak-and-eggs.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "chilaquiles",
    title: "Chilaquiles Verdes",
    cuisine: "texmex",
    category: "Breakfast",
    summary: "Crisp tortillas simmered just long enough in a green salsa to soften at the edge, topped with egg, crema, and cheese.",
    yieldText: "4 servings",
    prepMinutes: 20,
    cookMinutes: 20,
    ingredients: [
      "1 lb tomatillos, husked",
      "1 jalapeño",
      "1/2 onion",
      "2 garlic cloves",
      "1/2 cup cilantro",
      "1 teaspoon kosher salt",
      "12 corn tortillas, cut in wedges and fried or baked crisp",
      "4 fried eggs",
      "Crema or sour cream, crumbled cheese, and more cilantro"
    ],
    steps: [
      "Broil or roast the tomatillos, jalapeño, onion, and garlic until they blister. Blend with the cilantro and salt until mostly smooth.",
      "Simmer the salsa in a skillet for 5 minutes. Stir in a splash of water if it is too thick to coat a chip.",
      "Fold the crisp tortillas into the salsa and cook 1 minute. They should stay partly crisp.",
      "Serve at once with a fried egg, crema, cheese, and cilantro."
    ],
    notes: "If the tortillas sit in the salsa, you have casserole. Serve them right away.",
    image: "/images/chilaquiles.jpg",
    imageCredit: "Wikimedia Commons",
    sourceUrl: "https://en.wikipedia.org/wiki/Chilaquiles",
    sourceTitle: "Chilaquiles",
    youtube: "",
    family: true
  },
  {
    id: "breakfast-potatoes",
    title: "Skillet Breakfast Potatoes",
    cuisine: "texas",
    category: "Breakfast",
    summary: "Diced potatoes fried until the edges are crisp, with onion and a little chile. The side that belongs next to eggs.",
    yieldText: "4 servings",
    prepMinutes: 15,
    cookMinutes: 25,
    ingredients: [
      "1 1/2 lb potatoes, diced",
      "1 teaspoon kosher salt",
      "3 tablespoons oil",
      "1/2 onion, chopped",
      "1 teaspoon chili powder",
      "1/2 teaspoon black pepper",
      "2 tablespoons chopped cilantro or parsley"
    ],
    steps: [
      "Boil the potatoes in salted water for 5 minutes. Drain them well.",
      "Heat the oil in a wide skillet. Add the potatoes in one layer and leave them until the bottoms brown. Stir and brown again.",
      "Add the onion, chili powder, and pepper. Cook until the onion is soft and the potatoes are crisp at the edge.",
      "Salt to taste and scatter the herbs."
    ],
    notes: "Wet potatoes steam. Dry them after the boil.",
    image: "https://www.themealdb.com/images/media/meals/1550441882.jpg",
    imageCredit: "Photograph via TheMealDB",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "https://www.youtube.com/watch?v=BoD0TIO9nE4",
    family: true
  },
  {
    id: "cheddar-garlic-biscuits",
    title: "Fresh Cheddar Garlic Biscuits",
    cuisine: "texas",
    category: "Breakfast",
    summary: "Hot cheddar biscuits brushed with garlic butter. These are the fresh cheddar bay biscuits for the table.",
    yieldText: "12 biscuits",
    prepMinutes: 15,
    cookMinutes: 14,
    ingredients: [
      "2 cups flour",
      "1 tablespoon baking powder",
      "1 tablespoon sugar",
      "1 teaspoon kosher salt",
      "1/2 teaspoon garlic powder",
      "1/2 cup cold butter, grated or cut small",
      "1 1/2 cups shredded sharp cheddar",
      "3/4 cup cold buttermilk",
      "3 tablespoons melted butter",
      "1 garlic clove, minced",
      "1 tablespoon chopped parsley"
    ],
    steps: [
      "Heat the oven to 425°F. Stir the flour, baking powder, sugar, salt, and garlic powder.",
      "Cut in the cold butter. Toss in the cheddar. Stir in the buttermilk until a soft dough forms.",
      "Drop 12 scoops onto a lined sheet. Bake about 14 minutes, until risen and golden.",
      "Stir the melted butter, garlic, and parsley. Brush it over the hot biscuits and serve at once."
    ],
    notes: "They are best the hour they come out. The garlic butter is the whole point.",
    image: "/images/cheddar-garlic-biscuits.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "mexican-rice",
    title: "Tex-Mex Rice",
    cuisine: "texmex",
    category: "Sides",
    summary: "Rice toasted in oil, then cooked with tomato, onion, and broth until the grains stay separate.",
    yieldText: "6 servings",
    prepMinutes: 10,
    cookMinutes: 25,
    ingredients: [
      "2 tablespoons oil",
      "1 1/2 cups long-grain rice",
      "1/2 onion, chopped",
      "2 garlic cloves, minced",
      "1 cup tomato sauce or 2 chopped tomatoes",
      "2 1/2 cups chicken broth",
      "1 teaspoon kosher salt",
      "1/2 teaspoon ground cumin"
    ],
    steps: [
      "Toast the rice in the oil until it turns opaque and smells nutty.",
      "Add the onion and garlic and cook 1 minute.",
      "Stir in the tomato, broth, salt, and cumin. Bring to a boil.",
      "Cover, lower the heat, and cook 18 minutes. Rest off the heat 5 minutes, then fluff."
    ],
    notes: "Do not lift the lid while it cooks.",
    image: "/images/mexican-rice.jpg",
    imageCredit: "Wikimedia Commons",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "refried-beans",
    title: "Refried Pinto Beans",
    cuisine: "texmex",
    category: "Sides",
    summary: "Slow-cooked pintos mashed in their broth with onion and a little fat, for the side of every Tex-Mex plate.",
    yieldText: "8 servings",
    prepMinutes: 15,
    cookMinutes: 120,
    ingredients: [
      "1 lb dried pinto beans, picked over",
      "1 onion, halved, plus 1/2 onion chopped",
      "2 garlic cloves",
      "1 teaspoon kosher salt, plus more",
      "3 tablespoons bacon drippings, lard, or oil",
      "1/2 teaspoon ground cumin"
    ],
    steps: [
      "Cover the beans with water by 2 inches. Add the onion half and garlic. Simmer until the beans are soft, about 1 1/2 to 2 hours. Salt them in the last 20 minutes. Save the broth.",
      "Heat the fat and cook the chopped onion until soft.",
      "Add the beans a cup at a time and mash them, loosening with broth until they are creamy but not soupy.",
      "Stir in the cumin and salt to taste."
    ],
    notes: "Canned beans work in a pinch. Drain one can, then mash them the same way with a splash of the liquid.",
    image: "/images/refried-beans.jpg",
    imageCredit: "Wikimedia Commons",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "pico-de-gallo",
    title: "Pico de Gallo",
    cuisine: "texmex",
    category: "Sides",
    summary: "Chopped tomato, onion, jalapeño, cilantro, and lime. The salsa that belongs beside fajitas and breakfast tacos.",
    yieldText: "about 3 cups",
    prepMinutes: 15,
    cookMinutes: 0,
    ingredients: [
      "4 ripe tomatoes, seeded and diced",
      "1/2 white onion, finely chopped",
      "1 jalapeño, minced",
      "1/2 cup cilantro, chopped",
      "1 lime, juiced",
      "1 teaspoon kosher salt"
    ],
    steps: [
      "Stir everything together.",
      "Taste. Add salt or lime until it is bright, not watery.",
      "Rest 15 minutes so the juices come together. Serve the same day."
    ],
    notes: "If the tomatoes are watery, scoop out the seed pockets before you dice them.",
    image: "/images/pico-de-gallo.jpg",
    imageCredit: "Wikimedia Commons",
    sourceUrl: "https://en.wikipedia.org/wiki/Pico_de_gallo",
    sourceTitle: "Pico de gallo",
    youtube: "",
    family: true
  },
  {
    id: "pork-tamales",
    title: "Texas Pork Tamales",
    cuisine: "texmex",
    category: "Mains",
    summary: "Masa spread on a soaked corn husk, a stripe of chile pork, then steamed. A cold-weather family job.",
    yieldText: "about 2 dozen",
    prepMinutes: 90,
    cookMinutes: 90,
    ingredients: [
      "3 lb pork shoulder",
      "1 onion, quartered",
      "4 garlic cloves",
      "2 teaspoons kosher salt",
      "6 dried guajillo chiles, stemmed and seeded",
      "2 dried ancho chiles, stemmed and seeded",
      "1 teaspoon ground cumin",
      "1 teaspoon oregano",
      "4 cups masa harina",
      "1 1/2 teaspoons baking powder",
      "1 1/2 teaspoons salt",
      "1 cup lard, shortening, or oil",
      "3 to 3 1/2 cups warm pork broth",
      "About 30 dried corn husks, soaked until soft"
    ],
    steps: [
      "Cover the pork with water. Add the onion, garlic, and salt. Simmer until the pork shreds, about 2 hours. Save the broth. Shred the pork.",
      "Toast the chiles, cover them with hot water for 20 minutes, and blend with 1 cup of that water, the cumin, and oregano until smooth.",
      "Simmer the chile puree 10 minutes. Stir in the shredded pork and a splash of broth. It should be moist, not soupy.",
      "Beat the fat until fluffy. Mix the masa, baking powder, and salt. Beat in the fat, then enough warm broth that a dab of masa floats in cold water.",
      "Spread a thin layer of masa on the smooth side of a husk, add a stripe of pork, and fold the husk so the masa seals around the filling. Fold the tail up.",
      "Stand the tamales in a steamer, open end up, and steam 60 to 90 minutes, until the masa leaves the husk cleanly."
    ],
    notes: "This is a Saturday job. The filling and masa can be made the day before.",
    image: "/images/pork-tamales.jpg",
    imageCredit: "Wikimedia Commons",
    sourceUrl: "https://en.wikipedia.org/wiki/Tamale",
    sourceTitle: "Tamale",
    youtube: "",
    family: true
  },
  {
    id: "peach-cobbler",
    title: "Peach Cobbler",
    cuisine: "texas",
    category: "Sweets",
    summary: "Fresh or frozen peaches set on a buttered batter that rises around them. The Texas cobbler.",
    yieldText: "8 servings",
    prepMinutes: 20,
    cookMinutes: 45,
    ingredients: [
      "1/2 cup butter",
      "1 cup sugar",
      "1 cup flour",
      "1 tablespoon baking powder",
      "1/4 teaspoon salt",
      "1 cup milk",
      "4 cups sliced peaches, fresh or frozen",
      "1/2 cup sugar, for the fruit",
      "1 teaspoon cinnamon",
      "1 tablespoon lemon juice"
    ],
    steps: [
      "Heat the oven to 375°F. Put the butter in a 9-by-13-inch dish and set it in the oven until the butter melts.",
      "Stir 1 cup sugar, the flour, baking powder, salt, and milk into a smooth batter. Pour it over the melted butter. Do not stir.",
      "Toss the peaches with the remaining sugar, cinnamon, and lemon juice. Spoon them over the batter. Do not stir.",
      "Bake 40 to 45 minutes, until the batter is golden and cooked through at the center.",
      "Rest 15 minutes. Serve warm, with ice cream if you have it."
    ],
    notes: "The same batter takes any fruit. See the apple, blackberry, and sweet potato cobblers.",
    image: "/images/peach-cobbler.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "https://en.wikipedia.org/wiki/Cobbler_(food)",
    sourceTitle: "Cobbler",
    youtube: "https://www.youtube.com/watch?v=VzTZmSWlIJo",
    family: true
  },
  {
    id: "apple-cobbler",
    title: "Apple Cobbler",
    cuisine: "texas",
    category: "Sweets",
    summary: "Tart apples, cinnamon, and the same risen batter as the peach cobbler.",
    yieldText: "8 servings",
    prepMinutes: 25,
    cookMinutes: 50,
    ingredients: [
      "1/2 cup butter",
      "1 cup sugar",
      "1 cup flour",
      "1 tablespoon baking powder",
      "1/4 teaspoon salt",
      "1 cup milk",
      "6 cups sliced apples",
      "1/2 cup sugar",
      "1 teaspoon cinnamon",
      "1 tablespoon lemon juice"
    ],
    steps: [
      "Heat the oven to 375°F. Melt the butter in a 9-by-13-inch dish.",
      "Stir the 1 cup sugar, flour, baking powder, salt, and milk. Pour the batter over the butter. Do not stir.",
      "Toss the apples with the remaining sugar, cinnamon, and lemon juice. Spoon them over the batter.",
      "Bake 45 to 50 minutes, until the apples are tender and the crust is golden.",
      "The peach cobbler film in this book shows the batter. Use apples here."
    ],
    notes: "Firm apples hold their shape. A mix of tart and sweet is best.",
    image: "/images/apple-cobbler.jpg",
    imageCredit: "Wikimedia Commons",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "https://www.youtube.com/watch?v=VzTZmSWlIJo",
    family: true
  },
  {
    id: "blackberry-cobbler",
    title: "Blackberry Cobbler",
    cuisine: "texas",
    category: "Sweets",
    summary: "Blackberries, a little lemon, and the butter batter. A summer cobbler when the berries are in.",
    yieldText: "8 servings",
    prepMinutes: 15,
    cookMinutes: 45,
    ingredients: [
      "1/2 cup butter",
      "1 cup sugar",
      "1 cup flour",
      "1 tablespoon baking powder",
      "1/4 teaspoon salt",
      "1 cup milk",
      "5 cups blackberries",
      "1/2 cup sugar",
      "1 tablespoon lemon juice",
      "1 tablespoon flour, if the berries are very juicy"
    ],
    steps: [
      "Heat the oven to 375°F. Melt the butter in a 9-by-13-inch dish.",
      "Pour the batter of sugar, flour, baking powder, salt, and milk over the butter. Do not stir.",
      "Toss the berries with the remaining sugar, lemon juice, and the extra flour if they are swimming in juice. Spoon them over the batter.",
      "Bake about 45 minutes, until the crust is browned and the juices bubble.",
      "Watch the peach cobbler film for the batter, then use blackberries."
    ],
    notes: "Frozen berries work. Do not thaw them first.",
    image: "/images/blackberry-cobbler.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "https://www.youtube.com/watch?v=VzTZmSWlIJo",
    family: true
  },
  {
    id: "sweet-potato-cobbler",
    title: "Sweet Potato Cobbler",
    cuisine: "texas",
    category: "Sweets",
    summary: "Sliced sweet potatoes baked in a buttery sugar syrup under the cobbler batter. An old Texas sweet.",
    yieldText: "8 servings",
    prepMinutes: 25,
    cookMinutes: 55,
    ingredients: [
      "1/2 cup butter",
      "1 cup sugar",
      "1 cup flour",
      "1 tablespoon baking powder",
      "1/4 teaspoon salt",
      "1 cup milk",
      "3 large sweet potatoes, peeled and sliced thin",
      "3/4 cup sugar",
      "1 teaspoon cinnamon",
      "1/4 teaspoon nutmeg",
      "1/2 cup water"
    ],
    steps: [
      "Heat the oven to 375°F. Melt the butter in a deep baking dish.",
      "Pour in the batter of 1 cup sugar, flour, baking powder, salt, and milk. Do not stir.",
      "Toss the sweet potatoes with the remaining sugar, cinnamon, and nutmeg. Spread them over the batter and pour the water over the top.",
      "Bake 50 to 55 minutes, until the potatoes are tender and the top is browned. Cover with foil if the top browns before the potatoes are soft."
    ],
    notes: "Slice the potatoes thin, about 1/4 inch, or the center stays firm.",
    image: "/images/sweet-potato-cobbler.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "",
    family: true
  },
  {
    id: "peanut-butter-fudge",
    title: "Peanut Butter Fudge",
    cuisine: "texas",
    category: "Sweets",
    summary: "A pan of peanut butter fudge made with sweetened condensed milk. No thermometer.",
    yieldText: "about 24 squares",
    prepMinutes: 10,
    cookMinutes: 10,
    ingredients: [
      "1 can (14 oz) sweetened condensed milk",
      "1 cup creamy peanut butter",
      "1 cup peanut butter chips, or white chocolate chips",
      "1 teaspoon vanilla",
      "A pinch of salt",
      "Butter, for the pan"
    ],
    steps: [
      "Line an 8-inch square pan with parchment and butter it.",
      "Stir the condensed milk, peanut butter, and chips in a saucepan over low heat until the chips melt and the mixture is smooth. Do not let it boil.",
      "Take it off the heat. Stir in the vanilla and salt.",
      "Spread it in the pan. Chill until firm, about 2 hours. Cut in squares."
    ],
    notes: "Use regular creamy peanut butter. A natural peanut butter that separates will make the fudge oily.",
    image: "/images/peanut-butter-fudge.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "",
    sourceTitle: "",
    youtube: "https://www.youtube.com/watch?v=JrVR0OLpY-o",
    family: true
  },
  {
    id: "fried-ice-cream",
    title: "Fried Ice Cream",
    cuisine: "texmex",
    category: "Sweets",
    summary: "Scoops of ice cream frozen inside a cornflake crust, fried for a few seconds so the outside is hot and the center stays cold.",
    yieldText: "6 servings",
    prepMinutes: 30,
    cookMinutes: 5,
    ingredients: [
      "1 quart vanilla ice cream",
      "3 cups crushed cornflakes",
      "1/2 cup sugar",
      "1 teaspoon cinnamon",
      "2 eggs, beaten",
      "Oil for frying",
      "Honey or chocolate sauce"
    ],
    steps: [
      "Scoop 6 round balls of ice cream. Freeze them on a lined sheet until hard, at least 1 hour.",
      "Mix the cornflakes, sugar, and cinnamon. Roll each ball in egg, then in the flakes, then egg and flakes again so the coat is thick.",
      "Freeze again until the coating is solid, at least 2 hours and better overnight.",
      "Heat 2 inches of oil to 375°F. Fry one or two balls at a time for about 10 seconds, just until the crust is golden. Drain for a second and serve at once with honey or chocolate."
    ],
    notes: "If the ice cream is soft, it will melt in the oil. The second freeze is what makes this work.",
    image: "/images/fried-ice-cream.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: "https://en.wikipedia.org/wiki/Fried_ice_cream",
    sourceTitle: "Fried ice cream",
    youtube: "",
    family: true
  },
  {
    id: "garden-to-table",
    title: "From the Garden to the Table",
    cuisine: "garden",
    category: "Garden",
    summary: "How to keep a Texas garden bed, and what to do with fruit and vegetables the hour they are pulled.",
    yieldText: "a season",
    prepMinutes: 30,
    cookMinutes: 0,
    ingredients: [
      "A bed with sun most of the day",
      "Compost worked into the soil before planting",
      "Mulch to hold water",
      "A morning harvest basket",
      "Cool water for washing",
      "A refrigerator for what you will not cook or can today"
    ],
    steps: [
      "In spring and fall, work compost into the bed. Plant tomatoes, peppers, okra, squash, beans, and herbs where they get sun. Water at the soil, not on the leaves, and mulch so the ground does not bake.",
      "Pick in the morning, while the plants are still cool. Take fruit that is ripe that day. Leave anything moldy in the row, not in the basket.",
      "Shake off the dirt outside. Wash under cool water just before you cook, can, or pickle. Wet greens that sit in a bag spoil.",
      "Use tender beans, squash, okra, and herbs the same day. Tomatoes can sit on the counter out of the sun until they smell ripe. Potatoes, onions, and winter squash want a cool dark shelf, not the icebox.",
      "What you cannot eat in two days, pickle for the icebox or can by a tested method. Low-acid vegetables are not safe in a boiling-water bath."
    ],
    notes: "The canning plate in this book is for green beans. The pickle plate is for the icebox, and it is the everyday way to keep a big pull of cucumbers, okra, or beans.",
    image: "/images/garden-to-table.jpg",
    imageCredit: "Wikimedia Commons",
    sourceUrl: "https://nchfp.uga.edu/",
    sourceTitle: "National Center for Home Food Preservation",
    youtube: "",
    family: true
  },
  {
    id: "canning-green-beans",
    title: "Canning Garden Green Beans",
    cuisine: "garden",
    category: "Garden",
    summary: "Snap beans from the row, packed and processed in a pressure canner. A boiling-water bath is not safe for these.",
    yieldText: "about 7 quarts",
    prepMinutes: 60,
    cookMinutes: 25,
    ingredients: [
      "About 14 lb tender snap beans for 7 quarts, or 9 lb for 9 pints",
      "Boiling water",
      "Canning salt, optional: 1/2 teaspoon per pint or 1 teaspoon per quart",
      "Hot pint or quart jars, new lids, and bands",
      "A pressure canner with a dial gauge or a weighted gauge"
    ],
    steps: [
      "Wash the beans. Trim the ends. Leave them whole or snap them into 1-inch pieces. Discard rusty or wilted pods.",
      "Hot pack: cover the beans with boiling water and boil 5 minutes. Fill hot jars loosely, leaving 1 inch of headspace. Add salt if you want it. Cover with the hot cooking liquid, still leaving 1 inch.",
      "Raw pack: pack raw beans tightly into hot jars, leaving 1 inch. Add salt if you want it. Cover with boiling water, leaving 1 inch.",
      "Slide a knife around the inside of the jar to free bubbles. Wipe the rims. Set the lids and bands.",
      "Process in a pressure canner. Pints take 20 minutes. Quarts take 25 minutes. With a dial gauge, from sea level to 2,000 feet, use 11 pounds. With a weighted gauge, from sea level to 1,000 feet, use 10 pounds. Above those elevations, raise the pressure the way the National Center for Home Food Preservation shows.",
      "Let the canner cool and the pressure fall to zero before you open it. Cool the jars on a towel. After 12 to 24 hours, check that the lids sealed."
    ],
    notes: "There is no safe boiling-water process for green beans. Do not shorten the time. If you are above 1,000 or 2,000 feet, use the altitude table on the source page before you start. Read the canner manual for venting.",
    image: "/images/canning-green-beans.jpg",
    imageCredit: "Photograph for Lisa's Recipe Book",
    sourceUrl: nchfp,
    sourceTitle: "NCHFP snap beans",
    youtube: "",
    family: true
  },
  {
    id: "garden-pickles",
    title: "Refrigerator Garden Pickles",
    cuisine: "garden",
    category: "Garden",
    summary: "Cucumbers, okra, or green beans kept in a vinegar brine in the icebox. These are not shelf-canned pickles.",
    yieldText: "2 quarts",
    prepMinutes: 25,
    cookMinutes: 5,
    ingredients: [
      "1 1/2 lb small cucumbers, okra, or trimmed green beans",
      "4 garlic cloves, smashed",
      "2 teaspoons dill seed, or a handful of dill",
      "1 teaspoon black peppercorns",
      "1 teaspoon mustard seed",
      "1 cup white vinegar",
      "1 cup water",
      "1 tablespoon kosher salt",
      "1 tablespoon sugar"
    ],
    steps: [
      "Wash the vegetables. Pack them into two clean quart jars with the garlic, dill, peppercorns, and mustard seed.",
      "Heat the vinegar, water, salt, and sugar until the salt dissolves. Pour the hot brine over the vegetables so they are covered.",
      "Cool, then cap and refrigerate.",
      "Wait 2 days before you eat them. Keep them in the icebox and use them within a month."
    ],
    notes: "This brine is for the refrigerator only. It is not a canning recipe and the jars are not shelf-stable.",
    image: "/images/garden-pickles.jpg",
    imageCredit: "Wikimedia Commons",
    sourceUrl: "https://nchfp.uga.edu/",
    sourceTitle: "National Center for Home Food Preservation",
    youtube: "",
    family: true
  }
];
